name: provider_start
description: A production ready flutter application template for the provider architecture.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0"

scripts:
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  watch: flutter packages pub run build_runner watch --delete-conflicting-outputs
  test: flutter test
  analyze: flutter analyze --no-pub
  format: flutter format lib/**

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  stacked: ^1.7.6
  event_bus: '^1.1.1'

  # Utilities
  shared_preferences: ^0.5.8
  connectivity: ^0.4.9
  app_settings: ^4.0.2
  device_info: ^0.4.2+4
  path_provider: ^1.6.11
  hive_flutter: ^0.3.1
  built_value: ^7.1.0
  pedantic: ^1.9.0
  logging: ^0.11.4
  get_it: ^4.0.4
  mime: ^0.9.6+3
  get: ^3.4.3
  dio: ^3.0.10
  google_fonts: ^0.3.9
  url_launcher:
  cached_network_image: ^2.2.0+1
  typed_data: '^1.1.6'
  # UI Utilities
  flutter_screenutil: ^3.0.1
  mdi: ^4.0.0

  # UI Widgets
  flare_flutter: ^2.0.3

  auto_route: ^0.6.7
  oktoast: ^2.3.2
  flutter_swiper: ^1.1.6
  pull_to_refresh: ^1.6.3
  flutter_html: ^0.9.8
  flutter_staggered_animations: "^0.1.2"

  # proto
  protobuf: ^0.14.3
  crypto: ^2.1.5
  encrypt: ^4.0.2

  #https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.7+21
  #https://github.com/adee42/flutter_keyboard_visibility
  keyboard_visibility: ^0.5.6
  #https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^3.0.0
  # theme
  stacked_themes:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5
  built_value_generator: ^7.1.0
  hive_generator: ^0.7.0+2
  auto_route_generator: 0.6.10
  build_runner: ^1.10.0
  mockito: ^4.1.1
  logger: ^0.9.1
dependency_overrides:
  analyzer: 0.41.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/lang/
    - assets/images/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic